Adding math problem types
UCL-INGI/INGInious-problems-math pull request #11
Opened 2021-04-06 13:59 UTC by darkyne

Here is a summary of the main modifications:

1) The init file simply imports the math problem types and adds them to the choices.

2) Each math problem type (including MathProblem) is defined in its own file.

3) Some parts of MathProblem were reworked (such as is_equal) to add few bug fixes and allow more modularity (for other math problem types).

3) math_vector, math_matrix and math_interval were added, each in its own file, extending MathProblem.

4) math.js was adapted to add these new problem types.

5) html was a little bit modified to show a little format example and a button on the edit page showing the problem type and giving help information onclick.

The different commits are clear enough in my opinion, each coming with a complete comment (scroll down the long commit changes ^^).

Some usage examples are available here: https://github.com/darkyne/demo_math_problem_types
Everything is running fine on my local machine but I'll write more tests (probably unit-tests) to add credibility.

2021-04-07 12:54 UTC, Drumor requested changes
This is a "stylish" code review mostly

2021-04-07 12:54 UTC, Drumor commented on inginious_problems_math/static/math.js
> +
Lots of duplicate code, should be properly put in a method (e.g : studio_init_template_math... methods are quite the same)

2021-04-07 12:59 UTC, darkyne commented on inginious_problems_math/math_interval.py
> +        if len(borders) == 1 and left_open == right_open and not left_open: #Consider single element interval such as [5]
len would be enough to detect a single element interval but I prefered to check it is in the form of [a] because ]a[, [a[ or ]a] would have no mathematical meaning

2021-04-07 13:17 UTC, darkyne commented on inginious_problems_math/math_interval.py
> +        reworked_interval = cls.clear_interval(latex_interval)
Indeed, much more compact.

2021-04-07 13:19 UTC, darkyne commented on inginious_problems_math/math_interval.py
> +        if len(borders) == 1 and left_open == right_open and not left_open: #Consider single element interval such as [5]
that being said, I could maybe modify the condition to be:
len(borders)==1 and right_open==left_open==False 
if you want...
But I never tried triple comparison and am not sure about the correctness

2021-04-07 13:33 UTC, darkyne commented on inginious_problems_math/math_interval.py
> +        if latex_interval.startswith("\\left(") or latex_interval.startswith("\\left["):
I agree with you but actually I am not an expert about using regex and when I tried, I ran into other issues...

To make clear what I wanted to do:
I just want to remove the global () and [] symbols (those that surrounds the entire interval) without removing any of those symbols that may appear inside the interval itself (since border elements might be mathematical expressions including those symbols) knowing it may be missmatched symbols (like "(a,b]") and knowing such symbols may be encoded as (for example) '(' or by '\\left('.
Not sure why but sometimes the input was using one or the other format (probably related to the fact the student input was encoded manually or copy pasted from somewhere else I believe).
All this while encoding the type of symbol '[' or '(' before removing them (for inclusion/exclusion).

The easiest way to me ended up being the one you find in the code. Knowing I had to do many tests to figure out small unsuspected errors such as the importance of the if conditions order)

Since I encountered some little issues before coming to a correct result, I would prefer not to modify this method too much so I don't create a mess :D Or maybe if it's the last remaining improving element, you can improve it yourself? :/ 

Sorry for that.

2021-04-07 13:45 UTC, darkyne commented on inginious_problems_math/math_interval.py
> +        reworked = [latex_interval, left_open, right_open]
Yep, done.

2021-04-07 13:46 UTC, darkyne commented on inginious_problems_math/math_interval.py
> +        else:
True :) Done.

2021-04-07 13:47 UTC, darkyne commented on inginious_problems_math/math_matrix.py
> +        parsed_tab = list(map(cls.parse_line,latex_str_tab))
Done

2021-04-07 13:47 UTC, darkyne commented on inginious_problems_math/math_matrix.py
> +        return parsed_tab
Done

2021-04-07 13:50 UTC, darkyne commented on inginious_problems_math/math_matrix.py
> +    def is_equal(self, matrix1, matrix2):
I am not sure what you mean.
Here to see if two matrix are equal, I check every element one by one by calling the MathProblem.is_equal method that checks if two sympy expressions are equals (in the sence represents the same thing). For example if an element is written as "x+1" or "1+x" should give no different in the final score. Which is the reason why I use MathProblem.is_equal on every element (I mean pair of elements between the two matrix)

2021-04-07 14:21 UTC, darkyne commented on inginious_problems_math/math_matrix.py
> +    def is_equal(self, matrix1, matrix2):
Nevermind, I'm using sympy matrix type now.... Pushing when using these type everywhere.
Your remark about using == makes much more sense now.

2021-04-08 07:38 UTC, darkyne commented on inginious_problems_math/math_matrix.py
> +    def check_len(self, student_answer, correct_answer):
Done. Now using the shape attribute from Matrix

2021-04-08 08:33 UTC, darkyne commented on inginious_problems_math/static/math.js
> +
Done. I made studio_init_template_math to be generic for all the sub math types.
Same goes for math_create_answer. Now all the sub math types methods only call the generic ones.

2021-04-08 10:20 UTC, Drumor requested changes
some tiny improves

2021-04-08 10:20 UTC, Drumor commented on inginious_problems_math/static/math.js
> +    if (type=="math")
all this if can be replaced as:
`var row = $("#subproblem_"+type+"_answer").html();`

2021-04-08 10:20 UTC, Drumor commented on inginious_problems_math/math_interval.py
> +        if latex_interval.startswith("\\left(") or latex_interval.startswith("\\left["):
i'll propose you something in a few :)

2021-04-08 10:22 UTC, darkyne commented on inginious_problems_math/math_interval.py
>          reworked_interval = cls.clear_interval(latex_interval)
Damn you're right, don't know why I did not remove it.

2021-04-08 10:25 UTC, darkyne commented on inginious_problems_math/static/math.js
> +    if (type=="math")
Damn, that's much shorter and works perfectly :)

2021-04-08 12:09 UTC, darkyne commented
Obviously, I did some crap with commits management but I suggest to squash all these commits together as one when you are ok with the code :)

2021-04-09 09:30 UTC, Drumor approved these changes

2021-04-09 10:06 UTC, Drumor commented
Probably still needs some code review but for first iteration is good to me.

2021-04-09 10:06 UTC, merged

2021-04-12 08:09 UTC, anthonygego reviewed
No danger to leave these changes merged in master. However there are a few improvements to be done.

The main one is to return messages in case parsing failed for intervals and matrix. No need to be precise (a split-based parsing does not really allow to be precise), but at least warn the user that something went wrong.

2021-04-12 08:09 UTC, anthonygego commented on inginious_problems_math/templates/math_edit.html
> +<div id="Modal-PID" class="modal fade" role="dialog">
Please refine the modal id so that we avoid a maximum of conflicts. There may be tons of different subproblems templates here.

2021-04-12 08:09 UTC, anthonygego commented on inginious_problems_math/templates/math_edit_templates.html
> +                <label for="math-input-problem[PID][answers][CHOICE]" class="col-sm-2 control-label">{{_("Format example: "+ format)}}</label>
Same comment for future translations

2021-04-12 08:09 UTC, anthonygego commented on inginious_problems_math/tests.py
> +        self.assertEqual((int(MathProblem.parse_equation(self, "x").subs("x",10))),10)
Why do you need to pass ``self`` as argument ? This should be a class method. Moreover, ``self``is a ``TestCase``here.

2021-04-12 08:13 UTC, darkyne commented on inginious_problems_math/math_interval.py
> +__version__ = "0.1.dev0"
I'm not sure exactly how it works or if it should be put in every python file or not.
I just noticed it was there initially in the init.py. Maybe I should remove it from other python files ?

2021-04-12 08:14 UTC, anthonygego commented on inginious_problems_math/math_interval.py
> +__version__ = "0.1.dev0"
Yes, it should only be put once in the package ``__init__.py`` file.

2021-04-12 08:15 UTC, darkyne commented on inginious_problems_math/math_interval.py
> +    def parse_equation(cls, latex_str):
If you mean renaming the parse_equation function, it is actually redefining the generic parse_equation from MathProblem. I should have put something like @override or something like that. I'm not too used to conventions yet.

2021-04-12 08:18 UTC, anthonygego commented on inginious_problems_math/math_interval.py
> +    def parse_equation(cls, latex_str):
Yes, it should probably be renamed to a more generic one, to avoid confusion, as intervals or matrices are not equations.

2021-04-12 08:29 UTC, darkyne commented on inginious_problems_math/math_interval.py
> +    def parse_equation(cls, latex_str):
Renamed to parse_answer.

2021-04-12 10:12 UTC, darkyne commented on inginious_problems_math/math_interval.py
> +            return EmptySet
Done, raising an exception instead.

2021-04-12 10:13 UTC, darkyne commented on inginious_problems_math/math_interval.py
> +    def clear_interval(cls, latex_interval):
The function is now:
sanitize_interval_input(cls, latex_input)

2021-04-12 10:14 UTC, darkyne commented on inginious_problems_math/templates/math.html
> +<label class="col-sm-2 control-label">{{_("Format example: "+format)}}</label>
I am not sure what you mean by using format. 
Actually I don't know yet how translations are working :/

2021-04-12 10:15 UTC, darkyne commented on inginious_problems_math/templates/math_edit.html
> +        <button type="button" id="button-PID" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#Modal-PID" >{{ _(problem_type) }}</button>
What do you mean by friendly name ?
For example "matrix" instead of "math_matrix" ?

2021-04-12 10:17 UTC, anthonygego commented on inginious_problems_math/templates/math.html
> +<label class="col-sm-2 control-label">{{_("Format example: "+format)}}</label>
``"Format example : {}".format(format)``

2021-04-12 10:17 UTC, anthonygego commented on inginious_problems_math/templates/math_edit.html
> +        <button type="button" id="button-PID" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#Modal-PID" >{{ _(problem_type) }}</button>
For instance, yes. Something clean without ``_``

2021-04-12 10:18 UTC, darkyne commented on inginious_problems_math/templates/math.html
> +<label class="col-sm-2 control-label">{{_("Format example: "+format)}}</label>
ok ok, makes sense :)

2021-04-12 10:20 UTC, darkyne commented on inginious_problems_math/templates/math_edit.html
> +        <button type="button" id="button-PID" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#Modal-PID" >{{ _(problem_type) }}</button>
The string that is sent to the html is "math_matrix" for example.
Do you suggest to rework the string to remove the "math_" part with python included in html ?

2021-04-12 10:23 UTC, darkyne commented on inginious_problems_math/templates/math_edit.html
> +<div id="Modal-PID" class="modal fade" role="dialog">
I am not used to dynamic html ids yet...
Would "Modal-problem_type-PID" fit better ?

2021-04-12 10:26 UTC, anthonygego commented on inginious_problems_math/templates/math_edit.html
> +<div id="Modal-PID" class="modal fade" role="dialog">
For instance, yes

2021-04-12 10:27 UTC, anthonygego commented on inginious_problems_math/templates/math_edit.html
> +        <button type="button" id="button-PID" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#Modal-PID" >{{ _(problem_type) }}</button>
You can use the human-readable function ``get_type``from the ``Displayed...Problem``.

2021-04-12 10:36 UTC, darkyne commented on inginious_problems_math/templates/math_edit_templates.html
> +                <label for="math-input-problem[PID][answers][CHOICE]" class="col-sm-2 control-label">{{_("Format example: "+ format)}}</label>
Done.

2021-04-12 10:43 UTC, darkyne commented on inginious_problems_math/templates/math_edit.html
> +        <button type="button" id="button-PID" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#Modal-PID" >{{ _(problem_type) }}</button>
Now it displays the friendly name such as "matrix" instead of "math_matrix"

2021-04-12 11:04 UTC, darkyne commented on inginious_problems_math/tests.py
> +        self.assertEqual((int(MathProblem.parse_equation(self, "x").subs("x",10))),10)
That moment when I discover @classmethod actually has real impact, is not only for documentation...
Now all the parse functions are classmethods and do not require additionnal argument when called.