adding sets
UCL-INGI/INGInious-problems-math pull request #17
Opened 2021-04-29 13:52 UTC by darkyne

This adds the math-set problem type.
It represents sets of dicrete values.

A set can be expressed as explicit set: {1,2,3,4} or implicit set: {x|x²<25|N}.
When encoding the subproblem as a teacher, a radio checkbox allows to chose between both formats, automatically showing a correct format example for the student. 

Sadly, right now it is not able to easily compare explicit and implicit sets together since this would require to use the sympy solver which is very slow. In other words, the student has to follow the format example.

Explicit set:
Elements are written one by one.
Intersections and unions can be used. It first computes the unions then the intersections.
In other words, AuBnC = (AuB)nC and AnBuC = An(BuC).

Implicit set:
The format is {variable|condition|domain}
Condition can be composed such as (x²>25)&(x³<150)
Domain can be N, Z, Z+, Z-, R, Q or a specific set such as {4,5,6} or {x,x+1,3x}

Right now, it is advised to specify the domain to the student since for example {x|x<5|N} and {x|(x>0)&(x<5),Z} are not considered equals.
The != (latex \ne ) symbol is currently not working correctly for the conditions but it should probably not be useful for real cases.

All these informations are briefly described in the help button from the subproblem configuration page.

I believe it can be useful, especially the implicit format but it still has some important limitations.

2021-04-29 14:20 UTC, anthonygego requested changes
I know this is painful to fix, but you need to choose between inheritance or if clauses, otherwise this is "inheritance with design flaws"

2021-04-29 14:20 UTC, anthonygego commented on inginious_problems_math/math_problem.py
> +        self._set_type = content.get("set_type", None)
You should define this in the MathSetProblem class

2021-04-29 14:20 UTC, anthonygego commented on inginious_problems_math/templates/math_edit.html
> +{% if (problem_type == "math_set") %}
Again you should go on with inheritance and do this in a specific math set template.

2021-04-30 08:10 UTC, darkyne commented on inginious_problems_math/static/math.js
> +    else if (problem.type == "math_set")
This was already the case for math_matrix and math_interval. Do you suggest to remove all this if/elseif part and put each one in their corresponding studio_init function ?

2021-04-30 08:29 UTC, darkyne commented on inginious_problems_math/templates/math_edit.html
> +{% if (problem_type == "math_set") %}
I thought adding the radio buttons only when problem_type is "math_set" was the way to go here as it was the case for "tolerance". Do you suggest to have a specific html instead of having this if ?

Same goes for the "tolerance" which is only for "math" problem type.
Do you suggest to have a specific html file for each type (to remove the two if related to tolerance and set_type) ?

2021-04-30 08:32 UTC, anthonygego commented on inginious_problems_math/math_set.py
> +            final_set = Union(final_set, FiniteSet(MathProblem.parse_answer(element)))
Why do you need to instantiate a FiniteSet for each element and then make a Union of them ?
https://docs.sympy.org/latest/modules/sets.html#sympy.sets.sets.FiniteSet

2021-04-30 08:32 UTC, anthonygego commented on inginious_problems_math/math_set.py
> +    def parse_single_explicit_set(cls, eq):
Docstring would be useful here.

2021-04-30 08:32 UTC, anthonygego commented on inginious_problems_math/math_set.py
> +    def parse_explicit_set(cls, eq):
Docstring would be useful here.

2021-04-30 08:32 UTC, anthonygego commented on inginious_problems_math/math_set.py
> +            tab_2 = set_1.split('\\cup')
Add comment "unions"

2021-04-30 08:32 UTC, anthonygego commented on inginious_problems_math/math_set.py
> +        tab_1 = eq.split('\\cap')
Add comment "intersections"

2021-04-30 08:32 UTC, anthonygego commented on inginious_problems_math/math_set.py
> +            final_set_1 = simplify(Intersection(final_set_1, final_set_2))
Can simplify be called only once after having done all the operations, or not ?

2021-04-30 08:32 UTC, anthonygego commented on inginious_problems_math/math_set.py
> +        eq_tab = eq.split("|")
Maybe it would be fine for user to be returned a nice error message in case of missing elements than a index out of bounds error.

2021-04-30 08:32 UTC, anthonygego commented on inginious_problems_math/math_set.py
> +            if condition.startswith("(") and condition.endswith(")"):
`parse_answer` doesn't return the same thing with parantheses ?

2021-04-30 08:32 UTC, anthonygego commented on inginious_problems_math/math_set.py
> +                final_conditions = simplify(sympify(condition & final_conditions))
`&` ?? If this is correct, could you add more comment. `&` is supposed to be the bitwise and operator, this is not very clear.

2021-04-30 08:34 UTC, anthonygego commented on inginious_problems_math/static/math.js
> +    else if (problem.type == "math_set")
Yes, I clearly missed them during my previous reviews.

2021-04-30 08:34 UTC, anthonygego commented on inginious_problems_math/templates/math_edit.html
> +{% if (problem_type == "math_set") %}
You can define a specific block in the main jinja template and use inheritance to just sepcify what should be added in this block.

2021-04-30 08:35 UTC, darkyne commented on inginious_problems_math/math_set.py
> +            final_set = Union(final_set, FiniteSet(MathProblem.parse_answer(element)))
At first, I directly called FiniteSet(element1, element2...) but it had 2 issues:
- It only accepts sympy format, for example 2x returns a parsing error where 2*x is accepted
- It did not simplify elements (for example 10/2 is not converted to 5)

This is why I iterrate on elements and call Math.parse_answer on each.

2021-04-30 08:36 UTC, darkyne commented on inginious_problems_math/math_set.py
> +            final_set_1 = simplify(Intersection(final_set_1, final_set_2))
That's what I did at first try but I remember some cases not being correctly simplified. I'll test it again to detect if there is a specific case that caused problem.

2021-04-30 08:37 UTC, anthonygego commented on inginious_problems_math/math_set.py
> +            final_set = Union(final_set, FiniteSet(MathProblem.parse_answer(element)))
Yes, but you can first parse the table into a table a sympy objects and then instantiate the FiniteSet with the sympy objects list.

2021-04-30 08:42 UTC, darkyne commented on inginious_problems_math/math_set.py
> +                final_conditions = simplify(sympify(condition & final_conditions))
I remember I had issues with the conditions combinaisons with &.
This was  related to the fact ConditionSet accepts for example:
ConditionSet(x,(x>0)&(x<10),S.Naturals) without any problem (you can easily test sympy directly from their website by the way to check for formats etc) but refuses strings as inputs so ConditionSet("x", "(x>0)&(x<10)", S.Naturals) would return an error because they are not correct Sympy Expressions. I was not able to directly convert "(x>0)&(x<10)" into a sympy expression so I figured out tranforming "(x>0)" and "(x<10)" into two sympy expressions then adding the & symbol seemed to work...

But I will check this closer.
Still I remember trying parse_answer("{x|(x<0)&(x<5)|{1,2,3,4,5}}") and correctly returned {1,2,3,4}.

2021-04-30 08:49 UTC, darkyne commented on inginious_problems_math/math_set.py
> +            final_set = Union(final_set, FiniteSet(MathProblem.parse_answer(element)))
So, you suggest, for example, to split elements based on "," for example then get a table of sympy expression (using map to call MathProblem.parse_answer on each element) and finally FiniteSet(the_tab_of_sympy_objects) ?
This should, indeed, give the same result :)

2021-04-30 11:48 UTC, darkyne commented on inginious_problems_math/math_set.py
> +            final_set_1 = simplify(Intersection(final_set_1, final_set_2))
I don't remember exactly what changed compared to the last time I tested this but it works now with only simplifying at the return step :)

2021-04-30 12:07 UTC, anthonygego commented on inginious_problems_math/math_set.py
> +                final_conditions = simplify(sympify(condition & final_conditions))
Looks good : https://docs.sympy.org/latest/modules/logic.html

2021-04-30 13:40 UTC, darkyne commented on inginious_problems_math/math_set.py
> +            if condition.startswith("(") and condition.endswith(")"):
I am looking closer intho this.
Right now, I don't know exactly why, the Math.parse_answer returns the same thing for input with or without parenthesis for expressions such as 3x or (3x) etc... But when it's an equation or inequility, it seems to fail parsing with global parenthesis... 
Math.parse_answer("(3x+2)") no problem
Math.parse_answer("3x+2=0") no problem
Math.parse_answer("(3x+2=0)") parsing error

I believe the best choice here would be to correct this in the Math.parse_answer

2021-04-30 14:02 UTC, darkyne commented on inginious_problems_math/math_set.py
> +            if condition.startswith("(") and condition.endswith(")"):
Fixed by verifying if parenthesis are present around the entire answer, directly in Math.parse_answer.

2021-04-30 14:08 UTC, darkyne commented on inginious_problems_math/math_set.py
> +            if condition.startswith("(") and condition.endswith(")"):
Actually very wrong idea since it breakes expressions such as (3x+2)(2y+4) for example...

2021-04-30 14:31 UTC, darkyne commented on inginious_problems_math/math_set.py
> +            if condition.startswith("(") and condition.endswith(")"):
After discussion, the fact the Math.parse_answer does not accept equation/inequation when surrounded by useless parenthesis is not an issue. This means, this little verification here is required because, as opposed to Math.parse_answer, ConditionSet requires the format (condition1)&(condition2) with the parenthesis for the condition argument which should be removed when going into Math.parse_answer

2021-04-30 14:41 UTC, darkyne commented on inginious_problems_math/math_set.py
> +        """Parses"""
Oppsy gonna write some real docstring here.

2021-05-03 08:24 UTC, darkyne commented
Do you still see things to change here? :)

2021-05-03 09:45 UTC, anthonygego commented on inginious_problems_math/math_problem.py
> -        return template_helper.render("math_edit.html", template_folder=PATH_TO_TEMPLATES, key=key, problem_type=problem_type, friendly_type=friendly_type)
Another way not to change the interface and duplicate function in inherited classes is to specify the html template to use as a class attribute. This should probably be done for ``problem_type`` and ``friendly_type`` actually.

2021-05-03 09:45 UTC, anthonygego commented on inginious_problems_math/templates/math_edit.html
> +{% block math_set %}{% endblock %}
I would go for a more generic name such as ``math_extension``.

2021-05-03 11:52 UTC, darkyne commented on inginious_problems_math/math_problem.py
> -        return template_helper.render("math_edit.html", template_folder=PATH_TO_TEMPLATES, key=key, problem_type=problem_type, friendly_type=friendly_type)
I believe calling DisplayableMathProblem.show_editbox(...) while it's actually just a single line method that can easily be redefined is, at the end, not of big importance. After reflexion, I believe calling the template-helper directly from other types instead of calling DisplayableMathProblem.show_editbox(...) is simpler.

Only remaning little remark, concerning the fact having problem_type, html_file and friendly_type as class attributes like here:

![image](https://user-images.githubusercontent.com/17684696/116872704-a3112580-ac16-11eb-9292-379d339999ba.png)

Ideally friendly_type should be get via get_type_name which takes the language as argument (which is an attribute of the instance)...

I believe not having friendly_type as a class attribute is better, no ?

2021-05-03 11:59 UTC, anthonygego commented on inginious_problems_math/math_problem.py
> -        return template_helper.render("math_edit.html", template_folder=PATH_TO_TEMPLATES, key=key, problem_type=problem_type, friendly_type=friendly_type)
Indeed

2021-05-06 08:12 UTC, anthonygego commented on inginious_problems_math/math_interval.py
> +    problem_type = "math_interval"
It seems this is already defined in line 12.

2021-05-06 08:12 UTC, anthonygego commented on inginious_problems_math/math_matrix.py
> +    problem_type = "math_matrix"
Same remark. You can use the module-wide declaration if this is simpler for you.

2021-05-06 08:12 UTC, anthonygego commented on inginious_problems_math/static/math.js
> +    radio_set_type = document.getElementById("set_"+ set_type + "-"+pid);
If you could investigate why the jQuery selector does not work. There is probably something bad (non-standard) in the id  or even the html code for such strange thing to happen (maybe the dash, or duplicate...). If this is true, the behaviour may be different according to the browser implementation.

Moreover the vanilla js API is different from the jQuery one which is more "uniform".

2021-05-06 08:12 UTC, anthonygego commented on inginious_problems_math/static/math.js
> +    var element =  document.getElementById("format-"+pid);
Same remark here for jQuery.

2021-05-06 10:12 UTC, anthonygego commented
LGTM

2021-05-06 10:12 UTC, merged