Error_message visibility options
UCL-INGI/INGInious-problems-math pull request #32
Opened 2022-07-25 10:38 UTC by Manon-Oreins

Every math subproblem have now an option to modify when the error message has to be display to students.
3 possibilities :
       - always visible
       - visible after a certain number of attempts (ex : >= 3 attempts)
       - visible only after a certain date/hour

2022-07-27 06:48 UTC, anthonygego commented
Can you **rebase** this PR on ``master`` and solve conficts ?

2022-07-27 07:41 UTC, Manon-Oreins commented
Done

2022-07-27 08:17 UTC, anthonygego requested changes

2022-07-27 08:17 UTC, anthonygego commented on inginious_problems_math/math_problem.py
> +            return submission_date >= self._error_msg_hidden_until
I guess this will work with strings, but you'd rather at least check the date returned by the form is correctly formatted before saving it (in ``parse_problem``). Using the datetime library would still be a more robust choice as it would take into account the timezone subtleties, and even work with different timezones if the support is added in the future.

Furthermore, I'm not quite sure that was the expected discussed behaviour as this require the students to submit anew to see the hidden feedback (this means they should be allow to submit at that time), while the reStructredText directive allows the message to be displayed on already graded submissions.

2022-07-27 08:58 UTC, Manon-Oreins commented on inginious_problems_math/math_problem.py
> +            return submission_date >= self._error_msg_hidden_until
The hidden until rst directive doens't seem to work so I had to use something else instead.

2022-07-27 09:55 UTC, anthonygego commented on inginious_problems_math/math_problem.py
> +            return submission_date >= self._error_msg_hidden_until
Bypassing potential bugs is not a way to implement new features :smile:

But the question remains: which behaviour is wanted ?

2022-07-27 10:12 UTC, Manon-Oreins commented on inginious_problems_math/math_problem.py
> +            return submission_date >= self._error_msg_hidden_until
It is for students who want to practice/redo the exercises of a test. For example, once they have done the "Passeport Math" and after everyone have taken the test, they can retry the exercises they failed at and see the feedbacks (often showing the solution with some explanations). That was the initial idea of the hidden until feature. The number of attempts should be used when you don't wanna show the feedback containing the answer right after the first failed attempt.

2022-07-27 10:47 UTC, anthonygego commented on inginious_problems_math/math_problem.py
> +            return submission_date >= self._error_msg_hidden_until
OK. You can just add a check for the date format, then.

2022-07-27 13:55 UTC, Manon-Oreins commented on inginious_problems_math/math_problem.py
> +            return submission_date >= self._error_msg_hidden_until
I added the use of datetime.strptime to check the format of the date. About the timezone subtilities, I use the time from the state of each submission which I suppose already deals with it.

2022-07-27 14:16 UTC, anthonygego commented on inginious_problems_math/math_problem.py
> +                    print("ValE")
This print can be removed. 

According to the task edition code, all exceptions are caught and their error messages are displayed to the user, so you should be able to show the error to the user by raising any exception with the appropriate message, instead of silently setting a default value.

2022-07-27 14:38 UTC, Manon-Oreins commented on inginious_problems_math/math_problem.py
> +                    print("ValE")
So just raising the exception is enough ?

2022-07-27 14:46 UTC, anthonygego commented on inginious_problems_math/math_problem.py
> +                    print("ValE")
It **should**.

2022-07-27 14:52 UTC, Manon-Oreins commented on inginious_problems_math/math_problem.py
> +                    print("ValE")
This should be ok now then

2022-07-28 06:44 UTC, anthonygego requested changes
Currently it's possible for the user to select "hidden until" while not specifying any date. This date defaults to 2000-01-01 but is never shown to the user. You should either:
- forbid the ability to select hidden until without specifying any date;
- or store the default date so that it is shown in the editor once the task is saved.

2022-07-28 08:45 UTC, Manon-Oreins commented
I corrected it and did the same for the default number of attempts

2022-07-28 08:52 UTC, anthonygego commented on inginious_problems_math/math_problem.py
> +        print(self._error_msg_visibility_start)
You can remove this line and then it'll be OK :slightly_smiling_face:

2022-07-28 08:54 UTC, Manon-Oreins commented on inginious_problems_math/math_problem.py
> +        print(self._error_msg_visibility_start)
Aaaaah Sorry

2022-07-28 09:20 UTC, anthonygego approved these changes

2022-07-28 09:21 UTC, merged